language: java
dist: trusty
sudo: false
addons:
  apt:
    packages:
      - build-essential 
      - cmake 
      - ninja-build
      - pkg-config
      - ncurses-dev
      - libreadline-dev
      - libedit-dev
      - libgmp-dev
      - libssl-dev
      - unixodbc-dev
      - zlib1g-dev
      - libarchive-dev
      - libossp-uuid-dev
      - libxext-dev
      - libice-dev
      - libjpeg-dev
      - libxinerama-dev
      - libxft-dev
      - libxpm-dev
      - libxt-dev
      - libdb-dev
      - libpcre3-dev
      - libyaml-dev
      - openjdk-8-jdk
      - junit
homebrew:
    packages:
      - cmake
      - ninja
      - gmp
      - libarchive
      - readline
      - ossp-uuid
      - openssl
      - libyaml
      - unixodbc
      - berkeley-db
      - pcre
      - jpeg

before_install:
  - wget https://archive.apache.org/dist/maven/maven-3/3.5.0/binaries/apache-maven-3.5.0-bin.zip
  - unzip -qq apache-maven-3.5.0-bin.zip
  - export M2_HOME=$PWD/apache-maven-3.5.0
  - export PATH=$M2_HOME/bin:$PATH
  - echo "MAVEN_OPTS='-Dmaven.repo.local=$HOME/.m2/repository -Xmx1g -Dorg.slf4j.simpleLogger.showDateTime=true -Dorg.slf4j.simpleLogger.dateTimeFormat=HH:mm:ss:SSS'" > ~/.mavenrc
  - wget http://xsb.sourceforge.net/downloads/XSB.tar.gz
  - tar -xzvf XSB.tar.gz
  - chmod -R 777 /home/travis/build/prolobjectlink/prolobjectlink-jpi-ip-xsb/XSB
  - cd XSB/build/
  - ./configure
  - ./makexsb
  - cd ..
  - cd ..
  - wget https://www.dropbox.com/s/m4pgwk81p3w9cxr/interprolog.jar?dl=0 -O /home/travis/build/prolobjectlink/prolobjectlink-jpi-ip-xsb/interprolog.jar
  - mvn install:install-file -Dfile=interprolog.jar -DgroupId=com.declarativa.interprolog -DartifactId=interprolog -Dversion=2.2a4 -Dpackaging=jar

install:
  -

matrix:
   fast_finish: true
   include:
   -  jdk: oraclejdk8
      env:
      - DESC="Install Java 8"
      - CMD="mvn clean install site"
      
cache:
  directories:
  - ~/.m2
